clear all; close all; clc

%% Init
opt_visuals;

folder.root = '/Users/ilja/Library/CloudStorage/GoogleDrive-ilja.wagner1307@gmail.com/My Drive/mr_informationSamplingVisualManual/';
folder.data = strcat(folder.root, '2_data/');
folder.fig = ['/Users/ilja/Library/CloudStorage/GoogleDrive-ilja.wagner1307@gmail.com/My Drive/mr_informationSamplingVisualManual/' ...
              '5_outreach/manuscript/_submission_jnp/_revision/revision_accuracy'];

% Load data
data = load(strcat(folder.data, 'data_newPipeline.mat'));

%% Plot
plotDat = cat(3, ...
              [data.data.performance.proportionCorrect.easy(:,1) ...
               data.data.performance.proportionCorrect.easy(:,3)], ...
              [data.data.performance.proportionCorrect.difficult(:,1), ...
               data.data.performance.proportionCorrect.difficult(:,3)]);
xLabels = ["Proportion correct easy [visual]", ...
           "Proportion correct difficult [visual]"];
yLabels = ["Proportion correct easy [manual]", ...
           "Proportion correct difficult [manual]"];
nPanels = size(plotDat, 3);

hFig = figure('Units', 'Normalized', ...
              'OuterPosition', [0, 0, 0.40, 0.40]);
tiledlayout(1, 2);
for i = 1:nPanels % Panel
    % [r, p] = corrcoef(plotDat(:,1,i), plotDat(:,2,i), 'Rows', 'complete');
    [r, p] = corr(plotDat(:,1,i), plotDat(:,2,i), ...
                  "Rows", "Complete", ...
                  'type', 'Spearman');

    nexttile;
    line([0, 1], [0, 1], ...
         'LineStyle', '-', ...
         'LineWidth', plt.line.widthThin, ...
         'Color', plt.color.black, ...
         'HandleVisibility', 'off');
    hold on
    plot(plotDat(:,1,i), plotDat(:,2,i), ...
         'o', ...
         'MarkerSize', plt.marker.sizeSmall, ...
         'MarkerFaceColor', plt.color.black, ...
         'MarkerEdgeColor', plt.color.white, ...
         'LineWidth', plt.line.widthThin, ...
         'Color', plt.color.black)
    hold off
    if i == 1
        axis([0.70, 1, 0.70, 1], 'square');
        text(0.72, 1, ...
             ['r = ', num2str(round(r, 2)), ...
              '; p = ', num2str(round(p, 2))]);
    elseif i == 2
        axis([0.50, 1, 0.50, 1], 'square');
        text(0.55, 1, ...
             ['r = ', num2str(round(r, 2)), ...
              '; p = ', num2str(round(p, 2))]);
    end
    xlabel(xLabels(i));
    ylabel(yLabels(i));
    xticks(0:0.25:1);
    yticks(0:0.25:1);
    box off
end
saveas(gcf, strcat(folder.fig, '.png'));
close;
