function supportedTCMap = getSupportedTCMap

supportedTCMap = containers.Map({'MSVC120','MSVC140','MSVC150',  'MSVC160', ...
                       'MSVCPP120','MSVCPP140','MSVCPP150', 'MSVCPP160'},...
                      {'NVIDIA CUDA (w/Microsoft Visual C++ 2013) | nmake (64-bit Windows)',...
                       'NVIDIA CUDA (w/Microsoft Visual C++ 2015) | nmake (64-bit Windows)',...
                       'NVIDIA CUDA (w/Microsoft Visual C++ 2017) | nmake (64-bit Windows)',...
                       'NVIDIA CUDA (w/Microsoft Visual C++ 2019) | nmake (64-bit Windows)',...
                       'NVIDIA CUDA (w/Microsoft Visual C++ 2013) | nmake (64-bit Windows)',...
                       'NVIDIA CUDA (w/Microsoft Visual C++ 2015) | nmake (64-bit Windows)',...
                       'NVIDIA CUDA (w/Microsoft Visual C++ 2017) | nmake (64-bit Windows)',...
                       'NVIDIA CUDA (w/Microsoft Visual C++ 2019) | nmake (64-bit Windows)'});                
end                   
                   