clear all; close all; clc



%% Init
initFig;
folder.fig = strcat(folder.root, "5_outreach/manuscript/figures/fig6");

%% Panels A&B: predicted vs. empirical avg. proportion choices for easy target
idx.doubleVisual = 2;
idx.doubleManual = 4;
yLabels = ["Prop. choices easy [visual]", ...
           "Prop. choices easy [manual]"];
x = 0:1:8;
chancePerformance = 0.50;
nDistractorsEqualSetSize = 4;

hFig = figure;
tiledlayout(2, 2);
for p = 1:2 % Panel
    if p == 1 % Visual search experiment
        plt.color.condition = plt.color.green;

        emp = data.choice.target.proportionEasy(:,:,idx.doubleVisual);
        pred = probabilisticModel.pred.visual.propChoicesEasy;
    else
        plt.color.condition = plt.color.purple;

        emp = data.choice.target.proportionEasy(:,:,idx.doubleManual);
        pred = probabilisticModel.pred.manual.propChoicesEasy;
    end

    nexttile;
    errorbar(0:1:8, ...
             mean(emp, 1, 'omitnan'), ...
             ci_mean(emp), ...
            'o-', ...
            'MarkerSize', plt.marker.sizeLarge, ...
            'MarkerFaceColor', plt.color.condition(1,:), ...
            'MarkerEdgeColor', plt.color.white, ...
            'LineWidth', plt.line.widthThin, ...
            'CapSize', 0, ...
            'Color', plt.color.condition(1,:), ...
            'HandleVisibility', 'off')
    errorbar(0:1:8, ...
             mean(pred, 1, 'omitnan'), ...
             ci_mean(pred), ...
            'd-', ...
            'MarkerSize', plt.marker.sizeLarge, ...
            'MarkerFaceColor', plt.color.condition(1,:), ...
            'MarkerEdgeColor', plt.color.white, ...
            'LineWidth', plt.line.widthThin, ...
            'CapSize', 0, ...
            'Color', plt.color.condition(1,:), ...
            'HandleVisibility', 'off')
    % Plot some data at a non-sensical location to easily control marker
    % style in legend
    line([[(x(1) - 1); (x(end) + 1)], ...
          [nDistractorsEqualSetSize; nDistractorsEqualSetSize]], ...
         [[chancePerformance; chancePerformance], ...
          [0; 1]], ...
         'LineStyle', '-', ...
         'LineWidth', plt.line.widthThin, ...
         'Color', plt.color.black, ...
         'HandleVisibility', 'off');
    hold on
    % Plot some data at a non-sensical location and use this for the
    % legend; makes it easier to control visual appearance if legend
    % marker
    plot(999, 999, ...
         'o', ...
         'MarkerSize', plt.marker.sizeLarge, ...
         'MarkerFaceColor', plt.color.condition(1,:), ...
         'MarkerEdgeColor', 'None')
    plot(999, 999, ...
         'd', ...
         'MarkerSize', plt.marker.sizeLarge, ...
         'MarkerFaceColor', plt.color.condition(1,:), ...
         'MarkerEdgeColor', 'None')
    hold off
    axis([(x(1) - 1), (x(end) + 1), 0, 1], 'square');
    xlabel("# easy distractors");
    ylabel(yLabels(p));
    xticks(x(1):2:x(end));
    yticks(0:0.25:1);
    legend({"Empirical", "Model"}, 'Location', 'SouthWest');
    legend box off
    box off
end

%% Panels C&D: predicted vs. empirical avg. proportion fixations on chosen set
xLabels = ["Emp. prop. mov. chosen [visual]", ...
           "Emp. prop. mov. chosen [manual]"];
yLabels = ["Pred. prop. mov. chosen [visual]", ...
           "Pred. prop. mov. chosen [manual]"];
for p = 1:2 % Panel
    if p == 1 % Visual search experiment
        emp = mean(data.fixations.propFixOnChosenModelEval(:,:,idx.doubleVisual), 2, 'omitnan');
        pred = mean(probabilisticModel.pred.visual.propFixChosen, 2, 'omitnan');
    else
        emp = mean(data.fixations.propFixOnChosenModelEval(:,:,idx.doubleManual), 2, 'omitnan');
        pred = mean(probabilisticModel.pred.manual.propFixChosen, 2, 'omitnan');
    end

    nexttile;
    line([0, 1], [0, 1], ...
         'LineStyle', '-', ...
         'LineWidth', plt.line.widthThin, ...
         'Color', plt.color.black, ...
         'HandleVisibility', 'off');
    hold on
    plot(emp, pred, ...
         'o', ...
         'MarkerSize', plt.marker.sizeSmall, ...
         'MarkerFaceColor', plt.color.gray(2,:), ...
         'MarkerEdgeColor', plt.color.white, ...
         'LineWidth', plt.line.widthThin, ...
         'Color', plt.color.black)
    errorbar(mean(emp, 1, 'omitnan'), mean(pred, 1, 'omitnan'), ...
             ci_mean(pred), ci_mean(pred), ...
             ci_mean(emp), ci_mean(emp), ...
             'o', ...
             'MarkerSize', plt.marker.sizeLarge, ...
             'MarkerFaceColor', plt.color.black, ...
             'MarkerEdgeColor', 'none', ...
             'LineWidth', plt.line.widthThin, ...
             'CapSize', 0, ...
             'Color', plt.color.black, ...
             'HandleVisibility', 'off')
    [~, ~, h] = plotMean(emp, pred, plt.color.black);
    set(h(4), 'LineWidth', plt.line.widthThin);
    hold off
    axis([0.50, 1, 0.50, 1], 'square');
    xlabel(xLabels(p));
    ylabel(yLabels(p));
    xticks(0:0.25:1);
    yticks(0:0.25:1);
    box off
end

sublabel([], -20, -70);
opt.size = [35, 35];
opt.imgname = folder.fig;
opt.save = true;
prepareFigure(hFig, opt);
close;