function structTm = makeEMLRTStructTm()
%MATLAB Code Generation Private Function

%   Copyright 2018 The MathWorks, Inc.

%#codegen

structTm = struct("tm_nsec", 0, ...
    "tm_sec", 0, ...
    "tm_min", 0, ...
    "tm_hour", 0, ...
    "tm_mday", 0, ...
    "tm_mon", 0, ...
    "tm_year", 0, ...
    "tm_isdst", false);

coder.cstructname(structTm,'emlrtStructTm','extern','HeaderFile','emlrt.h');

%--------------------------------------------------------------------------
