function infSampling_plt_figThree(prop_choices_easy, prop_choices_easy_fit, slopesIntercepts, plt)

    %
    % Input
    %
    % Output
    % --

    %% Calculate confidence intervals of slopes and intercepts
    ci_regress = ci_mean(slopesIntercepts);


    %% Plot regression
    % Subjects 3 (nice curve), 13 (no strategy), 16 (always easy)
    sub_no = [16 3 13];

    fig_h = figure;
    for sp = 1:3

        curr_sub = sub_no(sp);

        subplot(2, 2, sp)
        infSampling_plt_propChoiceEasy(prop_choices_easy(:, curr_sub), plt)
        hold on
        plot(prop_choices_easy_fit(curr_sub, :, 1), prop_choices_easy_fit(curr_sub, :, 2), ...
             '-', ...
             'LineWidth', plt.lw.thick, ...
             'Color', plt.color.black);
        hold off
        title(['Subject ' num2str(curr_sub)]);

    end


    %% Plot slopes and intercepts
    subplot(2, 2, 4);
    plot(slopesIntercepts(:, 1), slopesIntercepts(:, 2), ...
         'o', ...
         'MarkerSize',      plt.size.mrk_ss, ...
         'MarkerEdgeColor', plt.color.white, ...
         'MarkerFaceColor', plt.color.o2, ...
         'LineWidth',       plt.lw.thin);
    hold on
    plot(mean(slopesIntercepts(:, 1), 'omitnan'), mean(slopesIntercepts(:, 2), 'omitnan'), ...
         'o', ...
         'MarkerSize',      plt.size.mrk_mean, ...
         'MarkerEdgeColor', plt.color.white, ...
         'MarkerFaceColor', plt.color.o1, ...
         'LineWidth',       plt.lw.thin);
    errorbar(mean(slopesIntercepts(:, 1), 'omitnan'), mean(slopesIntercepts(:, 2), 'omitnan'), ...
             ci_regress(1), ...
             'horizontal', ...
             'LineWidth', plt.lw.thick, ...
             'Color',     plt.color.o1);
    errorbar(mean(slopesIntercepts(:, 1), 'omitnan'), mean(slopesIntercepts(:, 2), 'omitnan'), ...
             ci_regress(2), ...
             'vertical', ...
             'LineWidth', plt.lw.thick, ...
             'Color',     plt.color.o1);
    hold off
    xlim([-0.5 0.5]);
    ylim([-0.2 0.1]);
    l_h(1) = line([-0.5, 0.5], [0 0], ...
                  'Color',     plt.color.c1, ...
                  'LineStyle', '--', ...
                  'LineWidth', plt.lw.thick);
    l_h(2) = line([0, 0], [-0.2 0.2], ...
                  'Color',     plt.color.c1, ...
                  'LineStyle', '--', ...
                  'LineWidth', plt.lw.thick);
    uistack(l_h, 'bottom');
    axis square;
    box off
    xlabel('Intercept (difficulty)');
    ylabel('Slope (set size)');


    %% Panel labels and save
    sublabel([], -10, -25);
    opt.size    = [25 25];
    opt.imgname = strcat(plt.name.aggr(1:end-14), 'figure3');
    opt.save    = plt.save;
    prepareFigure(fig_h, opt)
    close all

end