function infSampling_plt_scatterPropSaccOnStim(plt_dat, x_lab, y_lab, tit_lab, plt)

    % Plot proportion saccades on closest/distant stimulus
    % Input
    % plt_dat: two-column vector with data to plot on x- (:, 1) and y-axis
    %          (:, 2
    % x_lab    labels for x-axis
    % y_lab:   labels for y-axis
    % tit_lab: titles for subplots
    % plt:     struture with general plot settings
    % Output
    % --

    %% Create plot
    plot(plt_dat(:, :, 1), plt_dat(:, :, 2), ...
         'o',               ...
         'MarkerSize',      plt.size.mrk_ss, ...
         'MarkerFaceColor', plt.color.black, ...
         'MarkerEdgeColor', plt.color.white)
%     hold on
%     scatter(nanmean(plt_dat(:, :, 1)), nanmean(plt_dat(:, :, 2)), ...
%             300, ...
%             'MarkerFaceColor', plt.color.black, ...
%             'MarkerEdgeColor', plt.color.white)
%     hold off
    l_h(1) = line([0 1], [0.5 0.5], ...
                  'LineStyle', '--', ...
                  'LineWidth', 2, ...
                  'Color',     plt.color.c1);
    l_h(2) = line([0.5 0.5], [0 1], ...
                  'LineStyle', '--', ...
                  'LineWidth', 2, ...
                  'Color',     plt.color.c1);
    l_h(3) = line([0 1], [0 1], ...
                  'LineStyle', '--', ...
                  'LineWidth', 2, ...
                  'Color',     plt.color.c1);
    uistack(l_h, 'bottom') 
    axis([0 1 0 1], 'square')
    xticks(0:0.25:1)
    yticks(0:0.25:1)
    xlabel(x_lab)
    ylabel(y_lab)
    box off
    title(tit_lab)

end