function columnLabels = infSampling_colNames()

    % Defines colimn labels for .xls file
    % Input
    % --
    % Output
    % columnLabels: string vector with labels for the columns of exported
    %               files

    %% Define column labels
    columnLabels = ...
    ["Sub_No"; ...
     "Accuracy_overall"; ...
     "Accuracy_easy"; ...
     "Accuracy_hard"; ...
     "No_Sacc_easy_target"; ...                          5
     "No_Sacc_hard_target"; ...
     "No_Sacc_easy_dis_easy_target"; ...
     "No_Sacc_easy_dis_hard_target"; ...
     "No_Sacc_hard_dis_easy_target"; ...
     "No_Sacc_hard_dis_hard_target"; ...                 10
     "No_Sacc_easy_target_0_easy-8_hard"; ...
     "No_Sacc_easy_target_1-7"; ...
     "No_Sacc_easy_target_2-6"; ...
     "No_Sacc_easy_target_3-5"; ...
     "No_Sacc_easy_target_4-4"; ...                      15
     "No_Sacc_easy_target_5-3"; ...
     "No_Sacc_easy_target_6-2"; ...
     "No_Sacc_easy_target_7-1"; ...
     "No_Sacc_easy_target_8-0"; ...
     "No_Sacc_hard_target_0_easy-8_hard"; ...            20
     "No_Sacc_hard_target_1-7"; ...
     "No_Sacc_hard_target_2-6"; ...
     "No_Sacc_hard_target_3-5"; ...
     "No_Sacc_hard_target_4-4"; ...
     "No_Sacc_hard_target_5-3"; ...                      25
     "No_Sacc_hard_target_6-2"; ...
     "No_Sacc_hard_target_7-1"; ...
     "No_Sacc_hard_target_8-0"; ...
     "No_Sacc_easy_dis_+_easy_target_0_easy-8_hard"; ...
     "No_Sacc_easy_dis_+_easy_target_1-7"; ...           30
     "No_Sacc_easy_dis_+_easy_target_2-6"; ...
     "No_Sacc_easy_dis_+_easy_target_3-5"; ...
     "No_Sacc_easy_dis_+_easy_target_4-4"; ...
     "No_Sacc_easy_dis_+_easy_target_5-3"; ...
     "No_Sacc_easy_dis_+_easy_target_6-2"; ...           35
     "No_Sacc_easy_dis_+_easy_target_7-1"; ...
     "No_Sacc_easy_dis_+_easy_target_8-0"; ...
     "No_Sacc_easy_dis_+_hard_target_0_easy-8_hard"; ...
     "No_Sacc_easy_dis_+_hard_target_1-7"; ...
     "No_Sacc_easy_dis_+_hard_target_2-6"; ...           40
     "No_Sacc_easy_dis_+_hard_target_3-5"; ...
     "No_Sacc_easy_dis_+_hard_target_4-4"; ...
     "No_Sacc_easy_dis_+_hard_target_5-3"; ...
     "No_Sacc_easy_dis_+_hard_target_6-2"; ...
     "No_Sacc_easy_dis_+_hard_target_7-1"; ...           45
     "No_Sacc_easy_dis_+_hard_target_8-0"; ...
     "No_Sacc_hard_dis_+_easy_target_0_easy-8_hard"; ...
     "No_Sacc_hard_dis_+_easy_target_1-7"; ...
     "No_Sacc_hard_dis_+_easy_target_2-6"; ...
     "No_Sacc_hard_dis_+_easy_target_3-5"; ...           50
     "No_Sacc_hard_dis_+_easy_target_4-4"; ...
     "No_Sacc_hard_dis_+_easy_target_5-3"; ...
     "No_Sacc_hard_dis_+_easy_target_6-2"; ...
     "No_Sacc_hard_dis_+_easy_target_7-1"; ...
     "No_Sacc_hard_dis_+_easy_target_8-0"; ...           55
     "No_Sacc_hard_dis_+_hard_target_0_easy-8_hard"; ...
     "No_Sacc_hard_dis_+_hard_target_1-7"; ...
     "No_Sacc_hard_dis_+_hard_target_2-6"; ...
     "No_Sacc_hard_dis_+_hard_target_3-5"; ...
     "No_Sacc_hard_dis_+_hard_target_4-4"; ...           60
     "No_Sacc_hard_dis_+_hard_target_5-3"; ...
     "No_Sacc_hard_dis_+_hard_target_6-2"; ...
     "No_Sacc_hard_dis_+_hard_target_7-1"; ...
     "No_Sacc_hard_dis_+_hard_target_8-0"; ...
     "Search_time"; ...                                  65
     "Non_search_time"; ...
     "Fixation_time"; ...
     "Response_time"; ...
     "Search_time_easy_target"; ...
     "Non_search_time_easy_target"; ...                  70
     "Response_time_easy_target"; ...
     "Fixation_time_easy_target"; ...
     "Search_time_hard_target"; ...
     "Non_search_time_hard_target"; ...
     "Response_time_hard_target"; ...                    75
     "Fixation_time_hard_target"; ...
     "Prop_Choices_easy_target"; ...
     "Prop_Choices_hard_target"; ...
     "Prop_Choices_easy_target_0_easy-8_hard"; ...
     "Prop_Choices_easy_target_1-7"; ...                 80
     "Prop_Choices_easy_target_2-6"; ...
     "Prop_Choices_easy_target_3-5"; ...
     "Prop_Choices_easy_target_4-4"; ...
     "Prop_Choices_easy_target_5-3"; ...
     "Prop_Choices_easy_target_6-2"; ...                 85
     "Prop_Choices_easy_target_7-1"; ...
     "Prop_Choices_easy_target_8-0"; ...
     "Prop_Choices_hard_target_0_easy-8_hard"; ...
     "Prop_Choices_hard_target_1-7"; ...
     "Prop_Choices_hard_target_2-6"; ...                 90
     "Prop_Choices_hard_target_3-5"; ...
     "Prop_Choices_hard_target_4-4"; ...
     "Prop_Choices_hard_target_5-3"; ...
     "Prop_Choices_hard_target_6-2"; ...
     "Prop_Choices_hard_target_7-1"; ...                 95
     "Prop_Choices_hard_target_8-0"; ...
     "No_Trials"; ...
     "Lost_Time"; ...
     "No_excluded_trials"; ...
     "Accumulated_reward"];                            % 100

end