%% Define columns for log file
logCol.TRIAL_NO = 4;
logCol.N_TARGETS = 5;
logCol.DIFFICULTY_TARGET = 6;
logCol.DIFFICULTY_LEVEL_EASY = 7;
logCol.DIFFICULTY_LEVEL_DIFFICULT = 8;
logCol.GAP_POSITION_EASY = 9;
logCol.GAP_POSITION_DIFFICULT = 10;
logCol.GAP_POSITION_REPORTED = 11;
logCol.N_DISTRACTOR_EASY = 12;
logCol.N_DISTRACTOR_DIFFICULT = 13;
logCol.N_DISTRACTOR_OVERALL = 14;
logCol.STIMULUS_POSITION_X = 15:24;
logCol.STIMULUS_POSITION_Y = 25:34;
logCol.CUMULATIVE_TIMER = 35;
logCol.HIT_OR_MISS = 36;
logCol.SCORE = 37;
logCol.IS_FIXATION_ERROR = 38;