clear all;
all = [];
all = get_params(all);
all = read_data(all);
plot_data(all);
all = fit_model(all);
plot_paper(all);
plot_proposal(all);
plot_model(all);
all = fit_regression(all);
plot_regression(all);
save('model.mat','all');
