function assertValidDim(dim)
%MATLAB Code Generation Private Function

%   Checks that the argument DIM is a valid dimension argument.
%   Calls ASSERT.

%   Copyright 2006-2019 The MathWorks, Inc.
%#codegen

if isempty(coder.target)
    validateattributes(dim,{'numeric'}, ...
        {'scalar','real','integer','>=',1,'<=', ...
        intmax(coder.internal.indexIntClass)})
    return
end
coder.internal.allowEnumInputs;
coder.internal.allowHalfInputs;
coder.internal.prefer_const(dim);
coder.internal.assert(~coder.isenum(dim), ...
    'Coder:toolbox:eml_assert_valid_dim_1', ...
    'IfNotConst','Fail');
coder.internal.assert(coder.internal.isConst(size(dim)) && ...
    isscalar(dim), ...
    'Coder:toolbox:eml_assert_valid_dim_2', ...
    'IfNotConst','Fail');
coder.internal.assert(~isa(dim,'half'), ...
    'Coder:toolbox:DimCannotBeHalf');
coder.internal.assert(coder.internal.isBuiltInNumeric(dim) && ...
    isreal(dim) && ...
    dim >= 1 && dim == floor(dim) && ...
    dim <= intmax(coder.internal.indexIntClass), ...
    'MATLAB:getdimarg:dimensionMustBePositiveInteger');

