function p = isBuiltInNumeric(x)
%MATLAB Code Generation Private Function
%
%   Returns true if x belongs to any of the following classes: double,
%   single, int8, int16, int32, int64, uint8, uint16, uint32, uint64,
%   coder.internal.indexInt.  This function is used to exclude fixedpoint
%   and derived numeric types so that functions which are not qualified for
%   these types will not introduce untested and perhaps unintended
%   behaviors.  If a function should work for all numeric types, simply use
%   ISNUMERIC instead.

%   Copyright 2013-2019 The MathWorks, Inc.
%#codegen

coder.internal.allowHalfInputs;
coder.internal.allowEnumInputs;
p = isa(x,'double') || ...
    isa(x,'single') || ...
    isa(x,'int32')  || ...
    isa(x,'uint32') || ...
    isa(x,'int16')  || ...
    isa(x,'uint16') || ...
    isa(x,'int8')   || ...
    isa(x,'uint8')  || ...
    isa(x,'int64')  || ...
    isa(x,'uint64') || ...
    isa(x,'coder.internal.indexInt');
